movieApp/movieApp/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('ticketingApps.urls')),
]

movieApp/ticketingApps/urls.py
from django.urls import include, path, re_path
from django.conf.urls import url
from django.contrib import admin
from ticketingApps import views
from django.contrib.auth import views as auth_views
app_name = "ticketingApps"
urlpatterns = [
    re_path(r'^$', views.IndexPage.as_view(), name="index"),
    re_path(r'^theater/list/$', views.TheaterListView.as_view(), name="theater-list"),
    re_path(r'^theater/entry/$', views.AddTheater.as_view(), name="add-theater"),
    re_path(r'^showings/list/$', views.ShowingsList.as_view(), name="showings-list"),
    re_path(r'^showings/(?P<pk>\d+)/detail/$', views.ShowingDetail.as_view(), name="showing-detail"),
    re_path(r'^ticket/print/(?P<orderId>\d+)/$', views.PrintTicket.as_view(), name="print-ticket"),
    re_path(r'^theater/search/$',views.TheaterSearchResults.as_view(), name="search-theater"),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    re_path(r'^signup/$', views.Signup.as_view(), name='sign-up'),
    re_path(r'^hello/$',views.Welcome.as_view(), name='welcome'),
    re_path(r'^login_success/$',views.login_success,name='login_success'),
    re_path(r'^manager/$',views.ManagerLanding.as_view(),name='manager-landing'),
    re_path(r'^manager/theaters/$',views.ManagedTheaters.as_view(),name='theaters-filtered'),
    re_path(r'^manager/theaters/add_showing/(?P<theaterId>\d+)/$',views.AddShowing.as_view(),name='add-showing'),
    re_path(r'^manager/theaters/(?P<theaterId>\d+)/add_room/$', views.AddRoom.as_view(),name='add-room'),
    re_path(r'^manager/movie/add_movie/$', views.AddMovie.as_view(),name='add-movie'),
    re_path(r'^manager/movie/edit/(?P<pk>\d+)/$', views.EditMovie.as_view(), name='edit-movie'),
    re_path(r'^manager/movie/list/$',views.ListMovies.as_view(),name='list-movies'),
    re_path(r'^manager/movie/list/search/$', views.SearchMovies.as_view(),name='search-movies'),
    re_path(r'^manager/theater/(?P<pk>\d+)/delete/$', views.DeleteTheater.as_view(), name='delete-theater'),
    re_path(r'^manager/theater/(?P<pk>\d+)/details/$', views.TheaterDetail.as_view(), name='theater-detail'),
    re_path(r'^manager/theater/room/(?P<pk>\d+)/delete/$', views.DeleteRoom.as_view(), name='delete-room'),
    re_path(r'^manager/theater/showing/(?P<pk>\d+)/delete/$', views.DeleteShowing.as_view(), name='delete-showing'),
    re_path(r'^manager/theater/(?P<pk>\d+)/employee/add/$', views.AssociateEmployee.as_view(), name='add-employee'),
    re_path(r'^manager/showings/list/$', views.ManagedShowings.as_view(), name='managed-showings-list'),
    re_path(r'^manager/showings/list/filtered/$', views.ManagedShowingsSearchResults.as_view(), name='managed-showing-search'),
    re_path(r'^manager/pricing/group/create/$', views.CreatePricingGroup.as_view(), name="price-group-create"),
    re_path(r'^manager/pricing/point/create/$', views.CreatePricePoint.as_view(), name='price-point-create'),
    re_path(r'^manager/pricing/promocode/$', views.CreatePromoCode.as_view(), name='promo-code-create'),
    re_path(r'^manager/pricing/promocode/(?P<pk>\d+)/delete/$', views.DeletePromoCodes.as_view(), name='promo-code-delete'),
    re_path(r'^manager/pricing/promocode/list/$', views.ListPromoCodes.as_view(), name='promo-code-list'),
    re_path(r'^manager/pricing/group/list/$', views.ListPricingGroup.as_view(), name='price-group-list'),
    re_path(r'^showings/(?P<pk>\d+)/stats/$', views.ShowingAnalytics.as_view(), name='showing-stats'),
    re_path(r'^showings/(?P<showing>\d+)/order/$', views.SeatSelectionPage.as_view(), name='seat-selection'),
    re_path(r'^showings/order/ticketType/$', views.TicketTypeSelectionPage.as_view(), name='ticket-type'),
    re_path(r'^showings/order/payment/(?P<numberTix>\d+)/(?P<orderId>\d+|-\d+)$', views.SimpleOrderPage.as_view(), name='order'),
    re_path(r'^showings/order/charge/$', views.charge, name="charge"),
    re_path(r'^showings/search/$', views.ShowingsSearchResults.as_view(), name='showing-search'),
    re_path(r'^mytickets/$', views.UserTicketsListing.as_view(), name='ticket-list'),    
]

movieApp/ticketingApps/views/basic_views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView, DetailView
from django.urls import reverse_lazy, reverse
from ticketingApps.models import *
from ticketingApps.forms import *
from datetime import datetime
from django.contrib.auth.models import User
from django.conf import settings 
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils import timezone

#index/home page
class IndexPage(TemplateView):
    template_name = "ticketingApps/index.html"

#List of Theaters
class TheaterListView(ListView):
    #context_object_name = "theater_list"
    model = Theater
    form_class=TheaterForm
    paginate_by = 25
    template_name = "ticketingApps/theater_list.html"
    def TheaterList(self):
        return Theater.objects.all()
	
#List of Showings
class ShowingsList(ListView):
    model = Movieshowing
    fields = '__all__'
    template_name = "ticketingApps/showings_list.html"
    paginate_by = 25 
    def get_queryset(self):
        objs = Movieshowing.objects
        objs=objs.filter(time__gte=timezone.now())
        objs=objs.order_by('time')
        return objs

class ShowingsSearchResults(ListView):
    model = Movieshowing
    template_name="ticketingApps/showings_list.html"
    paginate_by = 25  
    def get_queryset(self):
        objs = Movieshowing.objects
        tName = self.request.GET["name"]
        tCity = self.request.GET["tCity"]
        tState = self.request.GET["tState"]
        mName = self.request.GET['mName']
        day = self.request.GET['day']
        objs=objs.all()
        if(tName!=""):
            objs=objs.filter(room__theater__theatername__icontains=tName)
        if(tCity!=""):
            objs=objs.filter(room__theater__theatercity__icontains=tCity)
        if(tState!=""):
            objs=objs.filter(room__theater__theaterstate__icontains=tState)
        if(mName!=""):
            objs=objs.filter(movie__movietitle__icontains=mName)
        if(day!=""):
            objs=objs.filter(time__range=(datetime.strptime(day,"%Y-%m-%d"),datetime.strptime(day,"%Y-%m-%d")+timedelta(days=1)))
        objs=objs.filter(time__gte=timezone.now())
        objs=objs.order_by('time')
        return objs.all()
class ShowingDetail(DetailView):
    model = Movieshowing
    template_name="ticketingApps/showing_detail.html"


#Print ticket page
class PrintTicket(TemplateView):
    template_name = "ticketingApps/print_ticket.html"
    def get_context_data(self, *args, **kwargs):
        context=super(PrintTicket, self).get_context_data(*args,**kwargs)
        #Movieshowing.objects.get(id=kwargs['showing'])
        # below we build context
        order = Order.objects.get(orderid=kwargs['orderId'])
        # add seats
        seats = Seatsbought.objects.filter(order=order)
        context['seats'] = seats
        # add orderid
        context['order'] = order
        # add movieshowing time
        if seats:
            movieshowing = seats[0].showing
        else:
            print("error")
        context['showing']=movieshowing
        context['showingtime'] = movieshowing.time
        # add room number
        room = movieshowing.room
        context['roomnumber'] = room.roomnumber
        # add movie
        movie = movieshowing.movie
        context['moviename'] = movie.movietitle
        # add theatre name
        theater = room.theater
        context['theatername'] = theater.theatername
        return context
class UserTicketsListing(LoginRequiredMixin,ListView):
    Model=Order
    template_name="ticketingApps/my_tickets.html"
    paginate_by=25
    def get_queryset(self):
        objs = Order.objects
        objs = objs.filter(profile__user=self.request.user, order_of__final=1).distinct()
        return objs.order_by('-order_of__showing__time')
    def get_context_data(self, *args,**kwargs):
        context=super(UserTicketsListing, self).get_context_data(*args,**kwargs)
        if(self.object_list.first()):
            context['valid']=True
        else:
            context['valid']=False
        return context

movieApp/ticketingApps/views/login_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic import TemplateView
from django.urls import reverse_lazy, reverse
from ticketingApps.models import *
from ticketingApps.forms import *
from datetime import datetime
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

class Signup(FormView):
    template_name='ticketingApps/signup.html'
    form_class= SignupForm
    success_url='/accounts/login/'
    def form_valid(self,form):
        form.save()
        return super().form_valid(form)
class Welcome(TemplateView):
    template_name='ticketingApps/hello.html'

def login_success(request):
    if request.user.profile.isemployee:
        return redirect('/manager/')
    else:
        return redirect('ticketingApps:index')
       

movieApp/ticketingApps/views/theater_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy, reverse
from ticketingApps.models import *
from ticketingApps.forms import *
from datetime import datetime
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django import forms
from django.http import Http404

class AddTheater(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Theater
    form_class=TheaterForm
    template_name = "ticketingApps/theater_form.html"
    success_url="/manager/theaters/"
    def test_func(self):
        return getattr(self.request.user.profile, "isemployee")
    def form_valid(self,form):
        theater=form.save(commit=False)
        theater.save()
        self.request.user.profile.theaters.add(theater)
        return super(AddTheater,self).form_valid(form)

class AddRoom(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model=Room
    form_class=AddRoomForm
    success_url='/manager/theaters/'
    def form_valid(self,form):
        form.instance.theater = Theater.objects.get(theaterid=self.kwargs["theaterId"])
        return super(AddRoom, self).form_valid(form)
    def test_func(self):
        return getattr(self.request.user.profile, "isemployee")
class TheaterSearchResults(ListView):
    model = Theater
    context_object_name = "theater_list"
    paginate_by = 25
    def get_queryset(self):
        objs = Theater.objects.filter(profile__user=self.request.user)
        tName = self.request.GET["name"]
        tCity = self.request.GET["tCity"]
        tState = self.request.GET["tState"]
        objs=objs.all()
        if(tName!=""):
            objs=objs.filter(theatername__icontains=tName)
        if(tCity!=""):
            objs=objs.filter(theatercity__icontains=tCity)
        if(tState!=""):
            objs=objs.filter(theaterstate__icontains=tState)
        return objs.all()
class DeleteTheater(LoginRequiredMixin, UserPassesTestMixin,DeleteView):
    model = Theater
    success_url='/manager/theaters/'
    template_name='ticketingApps/theater_delete_confirm.html'
    def test_func(self):
        return getattr(self.request.user.profile, "isemployee")
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(DeleteTheater, self).get_object()
        if obj not in self.request.user.profile.theaters.all():
            raise Http404
        return obj
class DeleteRoom(LoginRequiredMixin, UserPassesTestMixin,DeleteView):
    model = Room
    success_url='/manager/theaters/'
    template_name='ticketingApps/room_delete_confirm.html'
    def test_func(self):
        return getattr(self.request.user.profile, "isemployee")
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(DeleteRoom, self).get_object()
        if obj not in Room.objects.filter(theater__profile__user=self.request.user):
            raise Http404
        return obj
class TheaterDetail(LoginRequiredMixin,UserPassesTestMixin,DetailView):
    model = Theater
    template_name="ticketingApps/theater_detail.html"
    def test_func(self):
        return getattr(self.request.user.profile, "isemployee")
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(TheaterDetail, self).get_object()
        if obj not in Theater.objects.filter(profile__user=self.request.user):
            raise Http404("Theater not found.")
        return obj
class ManagedTheaters(LoginRequiredMixin,UserPassesTestMixin,ListView):
    model = Theater
    context_object_name = "theater_list"
    paginate_by = 25
    def test_func(self):
        return getattr(self.request.user.profile, "isemployee")
    def get_queryset(self):
        objs = self.request.user.profile.theaters
        return objs.all()

movieApp/ticketingApps/templates/ticketingApps/add_showing.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h3> Add New Showing </h3>
<form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <input type="submit" value="Save" class="button button-small">
    {% endbuttons %}
</form>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/charge.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1> Ticket Order </h1>
Thank you! Your order has been successful.<br>
<a href="{% url 'ticketingApps:print-ticket' orderId=orderIdH %}" class="button button-small">Print Tickets</a>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/create_price_point.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h3> Add New Price Point </h3>
<form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <input type="submit" value="Save" class="button button-small">
    {% endbuttons %}
</form>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/index.html
{% extends 'base.html' %}
{% block content %}
<h2> Welcome! </h2>
<br>
<ul>
		{% if not request.user.is_authenticated %}
		<a class="btn btn-login btn-block" href="accounts/login/" role="button"> Login </a><!--link to Login page-->
		<a class="btn btn-block" href="{% url 'ticketingApps:sign-up' %}" role="button"> Create Account </a><!--link to Add User form-->
		{% else %}
		<a class="btn btn-block" href="{% url 'ticketingApps:ticket-list'%}" role="button">My Tickets</a>
		{% endif %}
		<a class="btn btn-list btn-block" href="showings/list/" role="button"> Find a Movie </a><!--link to Showings List page-->
</ul>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/movie_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h3> Add New Movie </h3>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <input type="submit" value="Save" class="button button-small">
    {% endbuttons %}
</form>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/order.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{% if valid %}

<form action="{% url 'ticketingApps:charge' %}" method="post">
    {% csrf_token %}
    <h2> Confirm Your Order </h2>
    You are buying <b>{{numberTix}}</b> tickets to {{showingP.movie.movietitle}}.<br>
    The cost will be <b>${{cost}}</b>.<br>
    Your seats will be reserved for you for 8 minutes.<br>
    <input type="hidden" name="cost100" id="cost100" value="{{cost100}}">
    <input type="hidden" name="orderId" id="orderId" value="{{order.orderid}}">
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="{{ key }}"
        data-description="A Movie Ticket Charge"
        data-amount="{{cost100}}"
        data-locale="auto">
    </script>
</form>
{% else %}
Those seats are no longer available.
{% endif %}
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/promo_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<form method="post">{% csrf_token %}
        <p>Are you sure you want to delete promo code: {{ object.code }}?</p>
        <input type="submit" value="Confirm" class="button button-small">
    </form>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/room_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<form method="post">{% csrf_token %}
        <p>Are you sure you want to delete Room {{ object.roomnumber }} of {{object.theater.theatername}}?</p>
        <input type="submit" value="Confirm" class="button button-small">
    </form>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/seat_selection.html
{% extends 'base.html' %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>
    <script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
    <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>
    <script type='text/javascript'>
        //this is fine even though it complains. IDE doesn't understand js/Django/Vue combo
        var seatsBoughtJ = {{ seatsBought|safe }};
        var seatsPickedJ = {{seatsPicked|safe}};
        var rowsJ = {{numberRows}};
        var colsJ = {{numberCols}};
        var title = "{{showing.movie.movietitle}}";
        var mTime = "{{showing.time}}";
        var showingId = {{showing.id}}
    </script>
    <div id="vapp">
    {% endblock %}
    {% block styles %}
      <meta charset='utf-8' />
      <link
      type="text/css"
      rel="stylesheet"
      href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css"
    />
    <link
      type="text/css"
      rel="stylesheet"
      href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css"
    /> 
    {% endblock %}
    
    <body>
        {% block content %}
        {% load static %}
        {% if showing %}
      <h1>Seat Preview and Selection</h1>
      <h3>Seats for [[movieTitle]] on {{showing.time}}</h3>
      <h3>at {{showing.room.theater.theatername}} in Theater {{showing.room.roomnumber}} </h3>
        <br>
      <table class="flex-container" style="justify-content: flex-start">
        <tr>
            <td>
                    
                    <!-- guide box -->
                    <div style="width:600px;justify-content: center">
                        <h3>Guide:</h3>
                        <ul style="width:600px;justify-content: center" class="flex-container">
                        <li style="margin-top:15px;">Available:</li><li style="background:#0544f0;margin-left:12px;margin-right:30px" class="flex-item"></li>
                        <li style="margin-top:15px;">Selected:</li><li style="background:#00f133;margin-left:12px;margin-right:30px" class="flex-item"></li>
                        <li style="margin-top:15px;">Unavailable:</li><li style="background:#666666;margin-left:12px;margin-right:30px" class="flex-item"></li>
                    </ul>
                    </div>
                    <br>
            </td>
        </tr>

        <tr>
            <td>
                <div class="grid align-items-center">
                    <img :style="imgStyle" class="in-table mx-auto d-block"  src="{% static 'images/vague_screen.png' %}" alt="screen">
                        <table class="flex-container align-items-center">
                            <tr>
                            <template v-for="i in numberCols">
                                <td>
                                    <template v-for="j in numberRows">
                                        <table v-on:click="seatClick(i,j)" :class="[['item'+j.toString()+'-'+i.toString()+' flex-item']]" :bgcolor="[[picked[ j ][ i ] ]]">
                                        </table>
                                    </template>
                                </td>
                            </template>
                            </tr>
                        </table>  
                </div>
            </td>
            <td style="display: inline-block;vertical-align: top;">
                <div style="column-width: 300px;justify-content:center">
                        <h3>Pricing:</h3>
                        <table class="center">
                            {% for price in pGroup %}
                            <tr><td>{{price.name }}:</td><td>${{ price.price }}</td></tr>
                            {% endfor %}
                        </table>
                        <br>
                        <template v-if="numberTickets>0">Number of Tickets Selected: [[numberTickets]] <template v-if="numberTickets==10"><br>(Maximum of 10 tickets per order)</template></template>
                        <template v-if="numberTickets>0">
                            <form ref="buyForm" action="{% url 'ticketingApps:ticket-type' %}" method="get" style="width:105px">
                                {% csrf_token %}
                                <input type="hidden" name="toBuy" id="toBuy" :value="JSON.stringify(toBuy)">
                                <input type="hidden" name="showingId" id="showingId" :value="showing">
                                <button type="submit" style="width: 105px;" class="button button-small">Buy Tickets</button>
                            </form>
                        </template>
                        <template v-else>
                                <form style="width:105px"></form>
                        </template>
                </div>
            </td>
        </tr>
    </table>            
    <br>
    {% endif %}
    
</div>
{% endblock %}
    <!-- Our View App goes at the end of the document -->
    
    {% block endscripts %}
    <script>
    
    var vapp=new Vue({
            el: '#vapp',
            delimiters: ['[[', ']]'],
            data: { 
                movieTitle: title,
                time: mTime,
                numberRows: rowsJ,
                numberCols: colsJ,
                seatsBought: seatsBoughtJ,
                picked: seatsPickedJ,
                toBuy: {},
                showing: showingId,
                numberTickets: 0
            },
            computed: {
                imgStyle: function(){
                    return {width: (this.numberCols*48+5)+'px', 'min-height': "25px"}
                }
            },
            methods: {
                seatClick(i,j){
                    if(this.picked[String(j)][String(i)]=="#666666" || (this.numberTickets==10 && this.picked[j][i]=="#0544F0")){
                        //this seat is already bought
                    }else if(this.picked[j][i]=="#0544F0"){
                        this.picked[j][i]="#00F133"
                        this.toBuy[j*this.numberCols+i]=[j,i]
                        this.numberTickets++
                    }else{
                        this.picked[j][i]="#0544F0"
                        delete this.toBuy[j*this.numberCols+i]
                        this.numberTickets--
                    }
                },
            }
        });
    </script>
    {% endblock %}
    </body>

movieApp/ticketingApps/templates/ticketingApps/showing_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<form method="post">{% csrf_token %}
        <p>Are you sure you want to delete the showing of {{ object.movie.movietitle }} on {{object.time}}?</p>
        <input type="submit" value="Confirm" class="button button-small">
    </form>
    {% endblock %}

movieApp/ticketingApps/templates/ticketingApps/showing_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h3>Showing Detail</h3>
<h5>Showing Details</h5>
<div class="row">
    <div class="col-sm-8">
        Movie: {{object.movie.movietitle}}<br>
        Time: {{object.time}}<br>
        Theater: {{object.room.theater.theatername}}<br>
        Room: {{object.room.roomnumber}}<br>
        <br><br>
        <h5>Movie Details</h5>
        Runtime: {{object.movie.movieruntime}} minutes<br>
        Rating: {{object.movie.movierating}}<br>
        Release Date: {{object.movie.moviereleasedate}}<br>
        Genre: {{object.movie.moviegenre}}<br>
        Description: {{object.moviedescription}}<br>
        <br>
        <a href="{% url 'ticketingApps:seat-selection' showing=object.id %}"><button class="btn button button-small float-left" style="margin-top:.1em; margin-bottom:2em; margin-left:2em">Look at Seats</button></a>
    </div>
    <div class="col-sm-4">
	    {% if object.movie.poster %}
        <img src="{{ object.movie.poster.url }}" class="img-fluid" />
    	{% endif %}
    </div>
</div>
    {% endblock %}

movieApp/ticketingApps/templates/ticketingApps/theater_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<form method="post">{% csrf_token %}
        <p>Are you sure you want to delete {{ object.theatername }}?</p>
        <input type="submit" value="Confirm" class="button button-small">
    </form>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/theater_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h3> Add Theater </h3>
<form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <input type="submit" value="Save" class="button button-small">
    {% endbuttons %}
</form>
{% endblock %}

movieApp/ticketingApps/templates/ticketingApps/theater_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<form action="{% url 'ticketingApps:search-theater' %}" type="get" style="width:90%;text-align:center">
	<h3>Search:</h3>
	You can use as many or few fields as desired<br><br>
	<div>Theater Name: <input style="margin-left:1em;margin-bottom:1em;margin-right:1em;" id="name" type="text" name="name"></div>
	Theater City: <input style="margin-left:1em;margin-right:1em" id="tCity" type="text" name="tCity">
	Theater State: <input style="margin-left:1em;margin-right:1em;" id="tState" type="text" name="tState">
	<button id="theater_search_submit" type="submit" class="button button-small" style="margin-top:1em">Search</button><br>
</form>
<br>
<h3> Theater List </h3>
<table class="centered">
	{% for theater in theater_list %}
		<tr><td style="text-align: left">
			<b>{{theater.theatername}}</b>
			 located at {{theater.theaterstreet}} {{theater.theatercity}}, {{theater.theaterstate}}<br> 
			 <a class="button button-small float-right" style="margin-top:1em;margin-bottom:2em;margin-left:1em;margin-right:1em;display:inline" href="{%url 'ticketingApps:add-showing' theaterId=theater.theaterid%}">Add Showing</a>
			 <a class="button button-small float-right" style="margin-top:1em;margin-bottom:2em;margin-left:1em;margin-right:1em;display:inline" href="{% url 'ticketingApps:theater-detail' pk=theater.theaterid %}">More Settings</a>
        </td></tr>
	{% empty %}
		<li> No theaters yet. </li>
	{% endfor %}
</table>
<div class="pagination" style="justify-content: center">
		<span class="step-links">
			{% if page_obj.has_previous %}
				<a class="button button-small" href="?page=1">&laquo; first</a>
				<a class="button button-small" href="?page={{ page_obj.previous_page_number }}">previous</a>
			{% endif %}
	
			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
			</span>
	
			{% if page_obj.has_next %}
				<a class="button button-small" href="?page={{ page_obj.next_page_number }}">next</a>
				<a class="button button-small" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
			{% endif %}
		</span>
	</div>
{% endblock %}